services:
  jellyfin: # 8100
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      # NVIDIA GPU settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./config/jellyfin:/config
      - /mnt/mycloud/data/media:/data/media
    networks:
      - network
    ports:
      - 8100:8096      # HTTP WebUI
      # - 8920:8920    # HTTPS WebUI (optional)
      - 7359:7359/udp  # Local network discovery
      - 1900:1900/udp  # DLNA/Client service discovery
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  jellyseerr: # 8101
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      # - PORT=5055 #optional
    networks:
      - network
    ports:
      - 8101:5055
    volumes:
      - ./config/jellyseer:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  sonarr: # 8102
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - qbittorrent_network
      - network
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=America/New_York
    volumes:
      - ./config/sonarr:/config
      - /mnt/mycloud/data:/data
    ports:
      - 8102:8989
    restart: unless-stopped
  radarr: # 8103
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - qbittorrent_network
      - network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ./config/radarr:/config
      - /mnt/mycloud/data:/data
    ports:
      - 8103:7878
    restart: unless-stopped
  prowlarr: # 8104
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ./config/prowlarr:/config
    networks:
      - network
    ports:
      - 8104:9696
    restart: unless-stopped
  bazarr: # 8105
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=$[PGID}
      - TZ=America/New_York
    volumes:
      - ./config/bazarr:/config
      - /mnt/mycloud/data/media:/data/media
    networks:
      - network
    ports:
      - 8105:6767
    restart: unless-stopped
  byparr: # 8199
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    shm_size: 2gb
    networks:
      - network
    ports:
      - 8199:8191

networks:
  network:
    driver: bridge
  qbittorrent_network:
    external: true
