services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      # NVIDIA GPU settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./config:/config
      - /mnt/mycloud/data/media:/data/media
    ports:
      - 8096:8096      # HTTP WebUI
      # - 8920:8920    # HTTPS WebUI (optional)
      - 7359:7359/udp  # Local network discovery
      - 1900:1900/udp  # DLNA/Client service discovery
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
